### ISSUE TITLE
AutoML google_cloud_pipeline_components dataset creator not working anymore

### ISSUE THREAD

**Issue by wardVD** [GoogleCloudPlatform/vertex-ai-samples#1304]
Recently the AutoML `ImageDatasetCreateOp` from `google_cloud_pipeline_components` has started failing.

The example https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb does not seem to be working anymore.

![image](https://user-images.githubusercontent.com/2136274/204300234-6ab8836b-adc0-4aaa-8460-088e82cc2e81.png)

Error log:

```
2022-11-28 15:11:27.894 CET

service
Waiting for job to be provisioned.
2022-11-28 15:11:28.495 CET

service
Waiting for training program to start.
2022-11-28 15:11:29.797 CET

service
Job is preparing.
2022-11-28 15:12:50.585 CET

workerpool0-0.gcsfuse
Opening GCS connection...
2022-11-28 15:12:50.586 CET

workerpool0-0.gcsfuse
Mounting file system "gcsfuse"...
2022-11-28 15:12:50.587 CET

workerpool0-0.gcsfuse
File system has been successfully mounted.
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.project
2022-11-28 15:13:32.459 CET

workerpool0-0
silver-lead-310711
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.location
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.display_name
2022-11-28 15:13:32.459 CET

workerpool0-0
flowers
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.data_item_labels
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.gcs_source
2022-11-28 15:13:32.459 CET

workerpool0-0
gs://cloud-samples-data/vision/automl_classification/flowers/all_data_v2.csv
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.import_schema_uri
2022-11-28 15:13:32.459 CET

workerpool0-0
gs://google-cloud-aiplatform/schema/dataset/ioformat/image_classification_single_label_io_format_1.0.0.yaml
2022-11-28 15:13:32.459 CET

workerpool0-0
--method.labels
2022-11-28 15:13:32.459 CET

workerpool0-0
--resource_name_output_artifact_uri
2022-11-28 15:13:32.459 CET

workerpool0-0
gs://tmp_automl/tmp_ward/pipeline_root/flowers/510967010626/automl-image-training-v2-20221128141122/image-dataset-create_82490035240173568/dataset
2022-11-28 15:13:32.460 CET

workerpool0-0
Traceback (most recent call last):
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-11-28 15:13:32.460 CET

workerpool0-0
 "__main__", mod_spec)
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/runpy.py", line 85, in _run_code
2022-11-28 15:13:32.460 CET

workerpool0-0
 exec(code, run_globals)
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 290, in <module>
2022-11-28 15:13:32.460 CET

workerpool0-0
 main()
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 286, in main
2022-11-28 15:13:32.460 CET

workerpool0-0
 print(runner(args.cls_name, args.method_name, executor_input, kwargs))
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 242, in runner
2022-11-28 15:13:32.460 CET

workerpool0-0
 prepare_parameters(serialized_args[METHOD_KEY], method, is_init=False)
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 209, in prepare_parameters
2022-11-28 15:13:32.460 CET

workerpool0-0
 value = deserializer(value)
2022-11-28 15:13:32.460 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
2022-11-28 15:13:32.461 CET

workerpool0-0
 return _default_decoder.decode(s)
2022-11-28 15:13:32.461 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
2022-11-28 15:13:32.461 CET

workerpool0-0
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2022-11-28 15:13:32.461 CET

workerpool0-0
 File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
2022-11-28 15:13:32.461 CET

workerpool0-0
 raise JSONDecodeError("Expecting value", s, err.value) from None
2022-11-28 15:13:32.461 CET

workerpool0-0
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-11-28 15:13:55.001 CET

service
Job is running.
2022-11-28 15:13:55.125 CET

service
The replica workerpool0-0 exited with a non-zero status of 1. Termination reason: Error. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=510967010626&resource=ml_job%2Fjob_id%2F503452905341190144&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22503452905341190144%22
2022-11-28 15:17:41.421 CET

service
Finished tearing down training program.
2022-11-28 15:17:41.608 CET

service
Job failed.
```

**Comment by andrewferlitsch** [comment]
obsolete, notebook and component work as expected
