### ISSUE TITLE
notebooks/official/explainable_ai/gapic-custom_tabular_regression_online_explain.ipynb doesn't install tensorflow

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#140]
Logs: https://pantheon.corp.google.com/cloud-build/builds/98afe3ac-1589-4c10-bb9d-f28e1841558c?project=python-docs-samples-tests

```
Step #3: Copying file://notebooks/official/explainable_ai/gapic-custom_tabular_regression_online_explain.ipynb [Content-Type=application/octet-stream]...
Step #3: / [0 files][    0.0 B/139.4 KiB]                                                
/ [1 files][139.4 KiB/139.4 KiB]                                                
Step #3: Operation completed over 1 objects/139.4 KiB.                                    
Step #3: Uploaded output to: gs://cloud-build-notebooks-presubmit/executed_notebooks/PR_120/BUILD_831c33e0-bc70-4cd3-a3cf-a6d3e9b3c4ae/gapic-custom_tabular_regression_online_explain.ipynb
Step #3: Traceback (most recent call last):
Step #3:   File "/workspace/.cloud-build/execute_notebook_cli.py", line 34, in <module>
Step #3:     ExecuteNotebook.execute_notebook(
Step #3:   File "/workspace/.cloud-build/ExecuteNotebook.py", line 84, in execute_notebook
Step #3:     raise execution_exception
Step #3:   File "/workspace/.cloud-build/ExecuteNotebook.py", line 53, in execute_notebook
Step #3:     pm.execute_notebook(
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
Step #3:     raise_for_execution_errors(nb, output_path)
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
Step #3:     raise error
Step #3: papermill.exceptions.PapermillExecutionError: 
Step #3: ---------------------------------------------------------------------------
Step #3: Exception encountered at "In [33]":
Step #3: ---------------------------------------------------------------------------
Step #3: ModuleNotFoundError                       Traceback (most recent call last)
Step #3: /tmp/ipykernel_15/818968412.py in <module>
Step #3: ----> 1 import tensorflow as tf
Step #3:       2 
Step #3:       3 model = tf.keras.models.load_model(MODEL_DIR)
Step #3: 
Step #3: ModuleNotFoundError: No module named 'tensorflow'
Step #3: 
Finished Step #3
ERROR
ERROR: build step 3 "gcr.io/cloud-devrel-public-resources/python-samples-testing-docker:latest" failed: step exited with non-zero status: 1
```

**Comment by andrewferlitsch** [comment]
I merged the fix
