### ISSUE TITLE
Could not find lib geos_c or load any of its variants 

### ISSUE THREAD

**Issue by seandiacono** [GoogleCloudPlatform/vertex-ai-samples#1501]
## Expected Behavior

I am trying to run the SDK_Custom_Predict_and_Handler_SDK_Integration Notebook to understand how to use VertexA's Custom Prediction Routines (CPR). This notebook should train a sci-kit learn model, create a custom container with this model and create a custom predictor and handler and upload them to VertexAI. 

## Actual Behavior

I followed all the steps in the notebook however when I get to the cells that test the container locally I get the following error.

```
INFO:google.cloud.aiplatform.docker_utils.run:Container already exited, all container logs:
INFO:google.cloud.aiplatform.docker_utils.run:Traceback (most recent call last):
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
INFO:google.cloud.aiplatform.docker_utils.run:    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
INFO:google.cloud.aiplatform.docker_utils.run:    __import__(pkg_name)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform import initializer
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/initializer.py", line 34, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform.metadata import metadata
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/metadata/metadata.py", line 25, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform import pipeline_jobs
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 31, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform.metadata import artifact
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/metadata/artifact.py", line 25, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform import models
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/models.py", line 46, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.aiplatform import jobs
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/jobs.py", line 26, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud import bigquery
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.bigquery.client import Client
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 76, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.bigquery import _job_helpers
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/_job_helpers.py", line 24, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.bigquery import job
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/job/__init__.py", line 27, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.bigquery.job.copy_ import CopyJob
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/job/copy_.py", line 21, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from google.cloud.bigquery.table import TableReference
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 46, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from shapely import wkt  # type: ignore
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/shapely/wkt.py", line 6, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    from shapely import geos
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/shapely/geos.py", line 100, in <module>
INFO:google.cloud.aiplatform.docker_utils.run:    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
INFO:google.cloud.aiplatform.docker_utils.run:    libname, fallbacks or []))
INFO:google.cloud.aiplatform.docker_utils.run:OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
ERROR:google.cloud.aiplatform.prediction.local_endpoint:Exception during starting serving: ('Container exited before the first health check succeeded.', '', 1).
```

I tried to skip to the part that pushes the model to VertexAI and creates an endpoint however the model does not deploy to the endpoint and returns the following error as a message in the logs.

```
exec /usr/local/bin/python: exec format error
```

## Steps to Reproduce the Problem

1. Follow the sample in this [notebook
](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb)

## Specifications

- Version: Python 3.9.13
- Platform: MacOS Ventura M1

**Comment by michaelpulis** [comment]
On god

**Comment by andrewferlitsch** [comment]
@seandiacono I ran the notebook locally in Vertex Workbench and it ran fine to completion. It may be your environment, how did you run the notebook?

**Comment by andrewferlitsch** [comment]
closing due to inactivity
