### ISSUE TITLE
Pipeline Job Error when trying to get or create a GCS bucket for the pipeline output artifacts

### ISSUE THREAD

**Issue by kezirim** [GoogleCloudPlatform/vertex-ai-samples#2581]
## Expected Behavior
Pipeline job expected to run or be submitted successfully for execution.

## Actual Behavior
The following error is raised: 
ERROR:google.cloud.aiplatform.pipeline_jobs:Error when trying to get or create a GCS bucket for the pipeline output artifacts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/aiplatform/pipeline_jobs.py", line 404, in submit
    gcs_utils.create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist(
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/aiplatform/utils/gcs_utils.py", line 237, in create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist
    pipelines_bucket = storage.Blob.from_string(
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/storage/blob.py", line 412, in from_string
    raise ValueError("URI pattern must be gs://bucket/object")
ValueError: URI pattern must be gs://bucket/object

## Steps to Reproduce the Problem
Follow the steps in either of the two tutorials below:
1. [Intro KFP Pipeline](https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/pipelines_intro_kfp.ipynb?authuser=1#scrollTo=sjxaBix_2Ou7)
2. [Building a pipeline using KFP SDK](https://cloud.google.com/vertex-ai/docs/pipelines/build-pipeline?authuser=1#:~:text=%C2%A0%20%C2%A0%20%7D%0A)-,job,-.submit())

## Specifications

- Version: py38
- Platform: Linux/MacOS

**Comment by enesbesinci** [comment]
Im have faced the same issue today, did you find any solution for this?

**Comment by adam-bitstrapped** [comment]
same issue, any updates?

**Comment by enesbesinci** [comment]
do you use free trial version of gcp?

**Comment by hjerpe** [comment]
I'm having the same issue and I'm using a free trial version.

**Comment by enesbesinci** [comment]
I'm not sure but I think we gotta have not-free-trial version to run a pipeline on kubeflow, I have searched too amny times but I couldn't find any answer to fix this problem

**Comment by hjerpe** [comment]
@enesbesinci I was able to run my pipeline by adding the following permission:

`Vertex AI Service Agent`

However, the error message did not specify that this was the case. I also removed the `pipeline_root`, and instead let the pipeline artifacts be created at the default path.

**Comment by adam-bitstrapped** [comment]
@hjerpe Which service account did you add the permission to?

**Comment by gericdong** [comment]
Let us know if there is still an issue. Closed.

**Comment by pb-rategain-adara** [comment]
I am still experiencing this issue. I have added the 'BQ User', 'Storage Admin', 'Vertex Admin', and 'Vertex Service Agent' roles to the service account, as well as attempted to rerun the pipeline without `pipeline_root` arguments without success.

![Screenshot 2024-01-30 at 12-29-16 google_model_eval_tutorial ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/141957437/de380ef8-e0d5-4d0a-bf84-fcc0cc98a1a2)

**Comment by brandtoliver** [comment]
> I am still experiencing this issue. I have added the 'BQ User', 'Storage Admin', 'Vertex Admin', and 'Vertex Service Agent' roles to the service account, as well as attempted to rerun the pipeline without `pipeline_root` arguments without success.
> 
> ![Screenshot 2024-01-30 at 12-29-16 google_model_eval_tutorial ipynb](https://private-user-images.githubusercontent.com/141957437/300907142-de380ef8-e0d5-4d0a-bf84-fcc0cc98a1a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODMyMjIsIm5iZiI6MTcwNjg4MjkyMiwicGF0aCI6Ii8xNDE5NTc0MzcvMzAwOTA3MTQyLWRlMzgwZWY4LWUwZDUtNGQwYS1iZjg0LWZjYzBjYzk4YTFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDA4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGE1ZmMwOTkwOTIxNmFiYjk1YjkyYTMyYzhkZjA2MDUyYjQxNmQ0NTIyOTYzNDliZmY3NmJhYmM5ZDQ1Mzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d0sl4ZNqWDQqoYvjK0nQGyZWuV5FsnTG0KaGopeAyjM)

@pb-rategain-adara which version of google-cloud-aiplatform are you using? upgrading to the latest (1.40.0) solved it for me (see: https://github.com/googleapis/python-aiplatform/issues/2936)

**Comment by pb-rategain-adara** [comment]
Yes, I do have google-cloud-aiplatform version 1.40.0.

**Comment by AdamStormhardtGH** [comment]
confirmed this issue went away when running `google-cloud-aiplatform==1.73.0`

My base installation appeared to be google-cloud-aiplatform 1.24.1. I'm guessing due to compatibilities.

Also this is **unrelated** to free / paid tier. I'm on paid enterprise and the same issue occurred.
