### ISSUE TITLE
module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by mkandrewhuang301** [GoogleCloudPlatform/vertex-ai-samples#2889]
## Expected Behavior
When running pip3 install -r requirements.txt for google/multimodalembedding-001 it should install all the required dependencies

## Actual Behavior
(your_virtual_environment) (base) andrewhuang@Andrews-MacBook-Air-9 multimodalembedding % pip3 install -r requirements.txt                                     
Collecting absl-py==1.4.0 (from -r requirements.txt (line 1))
  Using cached absl_py-1.4.0-py3-none-any.whl.metadata (2.3 kB)
Collecting google-cloud-aiplatform==1.25.0 (from -r requirements.txt (line 2))
  Using cached google_cloud_aiplatform-1.25.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting proto-plus==1.22.2 (from -r requirements.txt (line 3))
  Using cached proto_plus-1.22.2-py3-none-any.whl.metadata (2.2 kB)
Collecting protobuf==4.23.0 (from -r requirements.txt (line 4))
  Using cached protobuf-4.23.0-cp37-abi3-macosx_10_9_universal2.whl.metadata (540 bytes)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached google_api_core-2.18.0-py3-none-any.whl.metadata (2.7 kB)
Collecting packaging>=14.3 (from google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting google-cloud-storage<3.0.0dev,>=1.32.0 (from google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached google_cloud_storage-2.16.0-py2.py3-none-any.whl.metadata (6.1 kB)
Collecting google-cloud-bigquery<4.0.0dev,>=1.15.0 (from google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached google_cloud_bigquery-3.21.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting google-cloud-resource-manager<3.0.0dev,>=1.3.3 (from google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached google_cloud_resource_manager-1.12.3-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting shapely<2.0.0 (from google-cloud-aiplatform==1.25.0->-r requirements.txt (line 2))
  Using cached Shapely-1.8.5.post1.tar.gz (200 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/andrewhuang/multimodalembedding/your_virtual_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/andrewhuang/multimodalembedding/your_virtual_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/andrewhuang/multimodalembedding/your_virtual_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/andrewhuang/multimodalembedding/your_virtual_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/lb/qf4p24b11jzc25yhkxb3j7_m0000gn/T/pip-build-env-73880a5q/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/lb/qf4p24b11jzc25yhkxb3j7_m0000gn/T/pip-build-env-73880a5q/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/lb/qf4p24b11jzc25yhkxb3j7_m0000gn/T/pip-build-env-73880a5q/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

## Steps to Reproduce the Problem

1. following  setup instructions here https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/multimodalembedding?_ga=2.88582616.2146459090.1713578704-2099533655.1713578704&project=carbon-theorem-420907 

## Specifications

- Version: python 3.9.6
- Platform: macOS

**Comment by gericdong** [comment]
@mkandrewhuang301 : can you please open the issue in https://issuetracker.google.com/issues? Thanks.
