### ISSUE TITLE
Deployment to Vertex AI fails

### ISSUE THREAD

**Issue by cl-juni** [GoogleCloudPlatform/vertex-ai-samples#3331]
I've been following [model_garden_pytorch_mistral_peft_tuning](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral_peft_tuning.ipynb) and running the saved model on a compute engine as

```bash
docker run -p 7080:7080 \
-v ~/.config/gcloud:/root/.config/gcloud \
-e GOOGLE_APPLICATION_CREDENTIALS="/root/.config/gcloud/application_default_credentials.json" \
-e GCLOUD_PROJECT="my-project" \
--gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20240724_0916_RC00 \
python -m vllm.entrypoints.api_server \
--host=0.0.0.0 \
--port=7080 \
--model="gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930" \
--tensor-parallel-size=1 \
--swap-space=16 \
--gpu-memory-utilization=0.9 \
--max-num-batched-tokens=4096 \
--max-model-len=4096
```

works well.
But trying to deploying it to Vertex AI through the notebook fails.

```python
vllm_args = [
    "--host=0.0.0.0",
    "--port=7080",
    f"--model={model_id}",
    f"--tensor-parallel-size={accelerator_count}",
    "--swap-space=16",
    "--gpu-memory-utilization=0.9",
    "--max-num-batched-tokens=4096",
    f"--max-model-len={max_model_len}",
]

model = aiplatform.Model.upload(
    display_name=model_name,
    serving_container_image_uri=VLLM_DOCKER_URI,
    serving_container_command=["python", "-m", "vllm.entrypoints.api_server"],
    serving_container_args=vllm_args,
    serving_container_ports=[7080],
    serving_container_predict_route="/generate",
    serving_container_health_route="/ping",
)

model.deploy(
    endpoint=endpoint,
    machine_type=machine_type,
    accelerator_type=accelerator_type,
    accelerator_count=accelerator_count,
    deploy_request_timeout=1800,
    service_account=service_account,
)
```

with `model_id="gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930"` and `VLLM_DOCKER_URI="us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20240724_0916_RC00"`.

Gives the logs

```log
ERROR 2024-07-26T09:57:23.182465553Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:23.182509183Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 402, in cached_file
ERROR 2024-07-26T09:57:23.182629823Z resolved_file = hf_hub_download(
ERROR 2024-07-26T09:57:23.182644367Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
ERROR 2024-07-26T09:57:23.182711601Z validate_repo_id(arg_value)
ERROR 2024-07-26T09:57:23.182718276Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
ERROR 2024-07-26T09:57:23.182823657Z raise HFValidationError(
ERROR 2024-07-26T09:57:23.182830095Z huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Use `repo_type` argument if needed.
ERROR 2024-07-26T09:57:23.182834863Z {}
ERROR 2024-07-26T09:57:23.182839632Z The above exception was the direct cause of the following exception:
ERROR 2024-07-26T09:57:23.182843208Z {}
ERROR 2024-07-26T09:57:23.182847023Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:23.182850837Z File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
ERROR 2024-07-26T09:57:23.182945966Z return _run_code(code, main_globals, None,
ERROR 2024-07-26T09:57:23.182968616Z File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
ERROR 2024-07-26T09:57:23.182979583Z exec(code, run_globals)
ERROR 2024-07-26T09:57:23.182989597Z File "/workspace/vllm/vllm/entrypoints/api_server.py", line 278, in <module>
ERROR 2024-07-26T09:57:23.183149814Z engine = AsyncLLMEngine.from_engine_args(
ERROR 2024-07-26T09:57:23.183159589Z File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
ERROR 2024-07-26T09:57:23.183279037Z engine_config = engine_args.create_engine_config()
ERROR 2024-07-26T09:57:23.183287382Z File "/workspace/vllm/vllm/engine/arg_utils.py", line 749, in create_engine_config
ERROR 2024-07-26T09:57:23.183618783Z model_config = ModelConfig(
ERROR 2024-07-26T09:57:23.183635234Z File "/workspace/vllm/vllm/config.py", line 153, in __init__
ERROR 2024-07-26T09:57:23.183714389Z self.hf_config = get_config(self.model, trust_remote_code, revision,
ERROR 2024-07-26T09:57:23.183726787Z File "/workspace/vllm/vllm/transformers_utils/config.py", line 44, in get_config
ERROR 2024-07-26T09:57:23.183790445Z config = AutoConfig.from_pretrained(
ERROR 2024-07-26T09:57:23.183799743Z File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 972, in from_pretrained
ERROR 2024-07-26T09:57:23.184022665Z config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:23.184032917Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 632, in get_config_dict
ERROR 2024-07-26T09:57:23.184229612Z config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:23.184611797Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
ERROR 2024-07-26T09:57:23.184635400Z resolved_config_file = cached_file(
ERROR 2024-07-26T09:57:23.184643507Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 466, in cached_file
ERROR 2024-07-26T09:57:23.184653759Z raise EnvironmentError(
ERROR 2024-07-26T09:57:23.184660434Z OSError: Incorrect path_or_model_id: 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
ERROR 2024-07-26T09:57:36.961709499Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:36.961771011Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 402, in cached_file
ERROR 2024-07-26T09:57:36.961842060Z resolved_file = hf_hub_download(
ERROR 2024-07-26T09:57:36.961860179Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
ERROR 2024-07-26T09:57:36.961921453Z validate_repo_id(arg_value)
ERROR 2024-07-26T09:57:36.961929798Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
ERROR 2024-07-26T09:57:36.962003231Z raise HFValidationError(
ERROR 2024-07-26T09:57:36.962009429Z huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Use `repo_type` argument if needed.
ERROR 2024-07-26T09:57:36.962015628Z {}
ERROR 2024-07-26T09:57:36.962021350Z The above exception was the direct cause of the following exception:
ERROR 2024-07-26T09:57:36.962026834Z {}
ERROR 2024-07-26T09:57:36.962032794Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:36.962038993Z File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
ERROR 2024-07-26T09:57:36.962142467Z return _run_code(code, main_globals, None,
ERROR 2024-07-26T09:57:36.962164640Z File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
ERROR 2024-07-26T09:57:36.962195873Z exec(code, run_globals)
ERROR 2024-07-26T09:57:36.962205171Z File "/workspace/vllm/vllm/entrypoints/api_server.py", line 278, in <module>
ERROR 2024-07-26T09:57:36.962359905Z engine = AsyncLLMEngine.from_engine_args(
ERROR 2024-07-26T09:57:36.962370157Z File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
ERROR 2024-07-26T09:57:36.962516546Z engine_config = engine_args.create_engine_config()
ERROR 2024-07-26T09:57:36.962523221Z File "/workspace/vllm/vllm/engine/arg_utils.py", line 749, in create_engine_config
ERROR 2024-07-26T09:57:36.962753295Z model_config = ModelConfig(
ERROR 2024-07-26T09:57:36.962763547Z File "/workspace/vllm/vllm/config.py", line 153, in __init__
ERROR 2024-07-26T09:57:36.962842464Z self.hf_config = get_config(self.model, trust_remote_code, revision,
ERROR 2024-07-26T09:57:36.962850332Z File "/workspace/vllm/vllm/transformers_utils/config.py", line 44, in get_config
ERROR 2024-07-26T09:57:36.963000774Z config = AutoConfig.from_pretrained(
ERROR 2024-07-26T09:57:36.963027477Z File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 972, in from_pretrained
ERROR 2024-07-26T09:57:36.963238954Z config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:36.963253498Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 632, in get_config_dict
ERROR 2024-07-26T09:57:36.963455915Z config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:36.963469743Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
ERROR 2024-07-26T09:57:36.963659524Z resolved_config_file = cached_file(
ERROR 2024-07-26T09:57:36.963670253Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 466, in cached_file
ERROR 2024-07-26T09:57:36.963825941Z raise EnvironmentError(
ERROR 2024-07-26T09:57:36.963834524Z OSError: Incorrect path_or_model_id: 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
ERROR 2024-07-26T09:57:58.043882369Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:58.043938875Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 402, in cached_file
ERROR 2024-07-26T09:57:58.043967247Z resolved_file = hf_hub_download(
ERROR 2024-07-26T09:57:58.043983221Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
ERROR 2024-07-26T09:57:58.044085264Z validate_repo_id(arg_value)
ERROR 2024-07-26T09:57:58.044095993Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
ERROR 2024-07-26T09:57:58.044132232Z raise HFValidationError(
ERROR 2024-07-26T09:57:58.044138908Z huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Use `repo_type` argument if needed.
ERROR 2024-07-26T09:57:58.044145107Z {}
ERROR 2024-07-26T09:57:58.044150352Z The above exception was the direct cause of the following exception:
ERROR 2024-07-26T09:57:58.044155836Z {}
ERROR 2024-07-26T09:57:58.044162273Z Traceback (most recent call last):
ERROR 2024-07-26T09:57:58.044168710Z File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
ERROR 2024-07-26T09:57:58.044300317Z return _run_code(code, main_globals, None,
ERROR 2024-07-26T09:57:58.044328212Z File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
ERROR 2024-07-26T09:57:58.044343471Z exec(code, run_globals)
ERROR 2024-07-26T09:57:58.044351339Z File "/workspace/vllm/vllm/entrypoints/api_server.py", line 278, in <module>
ERROR 2024-07-26T09:57:58.044475555Z engine = AsyncLLMEngine.from_engine_args(
ERROR 2024-07-26T09:57:58.044489383Z File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
ERROR 2024-07-26T09:57:58.044637203Z engine_config = engine_args.create_engine_config()
ERROR 2024-07-26T09:57:58.044649124Z File "/workspace/vllm/vllm/engine/arg_utils.py", line 749, in create_engine_config
ERROR 2024-07-26T09:57:58.044821500Z model_config = ModelConfig(
ERROR 2024-07-26T09:57:58.044831752Z File "/workspace/vllm/vllm/config.py", line 153, in __init__
ERROR 2024-07-26T09:57:58.044843673Z self.hf_config = get_config(self.model, trust_remote_code, revision,
ERROR 2024-07-26T09:57:58.044851541Z File "/workspace/vllm/vllm/transformers_utils/config.py", line 44, in get_config
ERROR 2024-07-26T09:57:58.044950723Z config = AutoConfig.from_pretrained(
ERROR 2024-07-26T09:57:58.044970273Z File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 972, in from_pretrained
ERROR 2024-07-26T09:57:58.045217275Z config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:58.045236587Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 632, in get_config_dict
ERROR 2024-07-26T09:57:58.045429229Z config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:57:58.045450925Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
ERROR 2024-07-26T09:57:58.045649290Z resolved_config_file = cached_file(
ERROR 2024-07-26T09:57:58.045667171Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 466, in cached_file
ERROR 2024-07-26T09:57:58.045831918Z raise EnvironmentError(
ERROR 2024-07-26T09:57:58.045848608Z OSError: Incorrect path_or_model_id: 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
ERROR 2024-07-26T09:58:31.136364459Z Traceback (most recent call last):
ERROR 2024-07-26T09:58:31.136416673Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 402, in cached_file
ERROR 2024-07-26T09:58:31.136467218Z resolved_file = hf_hub_download(
ERROR 2024-07-26T09:58:31.136496305Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
ERROR 2024-07-26T09:58:31.136596441Z validate_repo_id(arg_value)
ERROR 2024-07-26T09:58:31.136610984Z File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
ERROR 2024-07-26T09:58:31.136659860Z raise HFValidationError(
ERROR 2024-07-26T09:58:31.136668682Z huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Use `repo_type` argument if needed.
ERROR 2024-07-26T09:58:31.136675834Z {}
ERROR 2024-07-26T09:58:31.136680364Z The above exception was the direct cause of the following exception:
ERROR 2024-07-26T09:58:31.136683940Z {}
ERROR 2024-07-26T09:58:31.136688709Z Traceback (most recent call last):
ERROR 2024-07-26T09:58:31.136692762Z File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
ERROR 2024-07-26T09:58:31.136729240Z return _run_code(code, main_globals, None,
ERROR 2024-07-26T09:58:31.136738538Z File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
ERROR 2024-07-26T09:58:31.136792898Z exec(code, run_globals)
ERROR 2024-07-26T09:58:31.136803627Z File "/workspace/vllm/vllm/entrypoints/api_server.py", line 278, in <module>
ERROR 2024-07-26T09:58:31.136915206Z engine = AsyncLLMEngine.from_engine_args(
ERROR 2024-07-26T09:58:31.136937379Z File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
ERROR 2024-07-26T09:58:31.137065887Z engine_config = engine_args.create_engine_config()
ERROR 2024-07-26T09:58:31.137088060Z File "/workspace/vllm/vllm/engine/arg_utils.py", line 749, in create_engine_config
ERROR 2024-07-26T09:58:31.137236118Z model_config = ModelConfig(
ERROR 2024-07-26T09:58:31.137248992Z File "/workspace/vllm/vllm/config.py", line 153, in __init__
ERROR 2024-07-26T09:58:31.137259960Z self.hf_config = get_config(self.model, trust_remote_code, revision,
ERROR 2024-07-26T09:58:31.137272596Z File "/workspace/vllm/vllm/transformers_utils/config.py", line 44, in get_config
ERROR 2024-07-26T09:58:31.137356519Z config = AutoConfig.from_pretrained(
ERROR 2024-07-26T09:58:31.137376785Z File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 972, in from_pretrained
ERROR 2024-07-26T09:58:31.137632608Z config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:58:31.137654066Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 632, in get_config_dict
ERROR 2024-07-26T09:58:31.137857198Z config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
ERROR 2024-07-26T09:58:31.137876987Z File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
ERROR 2024-07-26T09:58:31.138065576Z resolved_config_file = cached_file(
ERROR 2024-07-26T09:58:31.138078451Z File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 466, in cached_file
ERROR 2024-07-26T09:58:31.138219356Z raise EnvironmentError(
ERROR 2024-07-26T09:58:31.138232946Z OSError: Incorrect path_or_model_id: 'gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

Even though the bucket is the same in both cases. (this is not only I've tried.).

Also it seems that the output from `workspace/vllm/vertex/gcs_download_launcher.sh` in the docker image does not output anything from vertex ai (but does on the compute engine). Maybe it's not running as it should?
What could be wrong?
How can I troubleshoot this?

**Comment by cl-juni** [comment]
[This one](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_llama3_1_deployment.ipynb) shows how it should be deployed. Instead of defining `serving_container_command=["python", "-m", "vllm.entrypoints.api_server"],` which seem to bypass `workspace/vllm/vertex/gcs_download_launcher.sh`. One defines the entrypoint like this
```python
    vllm_args = [
        "python",
        "-m",
        "vllm.entrypoints.api_server",
        "--host=0.0.0.0",
        "--port=7080",
        f"--model={model_id}",
        ...
    ]
```

**Comment by vicentefb** [comment]
Did you still use this as model_id ? `model_id="gs://my_bucket/tutorial_peft/tutorial_model/mistral-merged-model_20240724_085930"` i'm running into an validation issue with that: huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or
