### ISSUE TITLE
ModuleNotFoundError: No module named 'preprocess' when running the sample notebook SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb 

### ISSUE THREAD

**Issue by lanhwang** [GoogleCloudPlatform/vertex-ai-samples#740]
## Expected Behavior
The model should be deployed to local endpoint by running
```python
with local_model.deploy_to_local_endpoint(
    artifact_uri=f"{USER_MODEL_ARTIFACTS}",
) as local_endpoint:
    predict_response = local_endpoint.predict(
        request_file=INPUT_FILE,
        headers={"Content-Type": "application/json"},
    )

    health_check_response = local_endpoint.run_health_check()
```
## Actual Behavior
Got the error as below:
```
INFO:google.cloud.aiplatform.prediction.local_endpoint:Got the project id from the global config: gcp-cxbcsdev-nprd-34905.
INFO:google.cloud.aiplatform.docker_utils.run:Health check never succeeds, all container logs:
INFO:google.cloud.aiplatform.docker_utils.run:WARNING:root:Set the number of model server workers to 4.
INFO:google.cloud.aiplatform.docker_utils.run:INFO:     Uvicorn running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:google.cloud.aiplatform.docker_utils.run:INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:google.cloud.aiplatform.docker_utils.run:INFO:     Started parent process [1]
INFO:google.cloud.aiplatform.docker_utils.run:INFO:uvicorn.error:Started parent process [1]
INFO:google.cloud.aiplatform.docker_utils.run:Process SpawnProcess-3:
INFO:google.cloud.aiplatform.docker_utils.run:Traceback (most recent call last):
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
INFO:google.cloud.aiplatform.docker_utils.run:    self.run()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
INFO:google.cloud.aiplatform.docker_utils.run:    self._target(*self._args, **self._kwargs)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
INFO:google.cloud.aiplatform.docker_utils.run:    target(sockets=sockets)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return asyncio.run(self.serve(sockets=sockets))
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return loop.run_until_complete(main)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
INFO:google.cloud.aiplatform.docker_utils.run:    return future.result()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
INFO:google.cloud.aiplatform.docker_utils.run:    config.load()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 464, in load
INFO:google.cloud.aiplatform.docker_utils.run:    self.loaded_app = self.loaded_app()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/model_server.py", line 75, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    os.environ.get("AIP_STORAGE_URI"), predictor=predictor_class
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/handler.py", line 95, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    self._predictor.load(artifacts_uri)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/app/src_dir_handler_sdk/predictor.py", line 22, in load
INFO:google.cloud.aiplatform.docker_utils.run:    preprocessor = pickle.load(f)
INFO:google.cloud.aiplatform.docker_utils.run:ModuleNotFoundError: No module named 'preprocess'
INFO:google.cloud.aiplatform.docker_utils.run:Process SpawnProcess-4:
INFO:google.cloud.aiplatform.docker_utils.run:Traceback (most recent call last):
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
INFO:google.cloud.aiplatform.docker_utils.run:    self.run()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
INFO:google.cloud.aiplatform.docker_utils.run:    self._target(*self._args, **self._kwargs)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
INFO:google.cloud.aiplatform.docker_utils.run:    target(sockets=sockets)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return asyncio.run(self.serve(sockets=sockets))
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return loop.run_until_complete(main)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
INFO:google.cloud.aiplatform.docker_utils.run:    return future.result()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
INFO:google.cloud.aiplatform.docker_utils.run:    config.load()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 464, in load
INFO:google.cloud.aiplatform.docker_utils.run:    self.loaded_app = self.loaded_app()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/model_server.py", line 75, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    os.environ.get("AIP_STORAGE_URI"), predictor=predictor_class
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/handler.py", line 95, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    self._predictor.load(artifacts_uri)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/app/src_dir_handler_sdk/predictor.py", line 22, in load
INFO:google.cloud.aiplatform.docker_utils.run:    preprocessor = pickle.load(f)
INFO:google.cloud.aiplatform.docker_utils.run:ModuleNotFoundError: No module named 'preprocess'
INFO:google.cloud.aiplatform.docker_utils.run:Process SpawnProcess-1:
INFO:google.cloud.aiplatform.docker_utils.run:Traceback (most recent call last):
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
INFO:google.cloud.aiplatform.docker_utils.run:    self.run()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
INFO:google.cloud.aiplatform.docker_utils.run:    self._target(*self._args, **self._kwargs)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
INFO:google.cloud.aiplatform.docker_utils.run:    target(sockets=sockets)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return asyncio.run(self.serve(sockets=sockets))
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return loop.run_until_complete(main)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
INFO:google.cloud.aiplatform.docker_utils.run:    return future.result()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
INFO:google.cloud.aiplatform.docker_utils.run:    config.load()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 464, in load
INFO:google.cloud.aiplatform.docker_utils.run:    self.loaded_app = self.loaded_app()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/model_server.py", line 75, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    os.environ.get("AIP_STORAGE_URI"), predictor=predictor_class
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/handler.py", line 95, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    self._predictor.load(artifacts_uri)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/app/src_dir_handler_sdk/predictor.py", line 22, in load
INFO:google.cloud.aiplatform.docker_utils.run:    preprocessor = pickle.load(f)
INFO:google.cloud.aiplatform.docker_utils.run:ModuleNotFoundError: No module named 'preprocess'
INFO:google.cloud.aiplatform.docker_utils.run:Process SpawnProcess-2:
INFO:google.cloud.aiplatform.docker_utils.run:Traceback (most recent call last):
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
INFO:google.cloud.aiplatform.docker_utils.run:    self.run()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
INFO:google.cloud.aiplatform.docker_utils.run:    self._target(*self._args, **self._kwargs)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
INFO:google.cloud.aiplatform.docker_utils.run:    target(sockets=sockets)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return asyncio.run(self.serve(sockets=sockets))
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
INFO:google.cloud.aiplatform.docker_utils.run:    return loop.run_until_complete(main)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
INFO:google.cloud.aiplatform.docker_utils.run:    return future.result()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
INFO:google.cloud.aiplatform.docker_utils.run:    config.load()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 464, in load
INFO:google.cloud.aiplatform.docker_utils.run:    self.loaded_app = self.loaded_app()
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/model_server.py", line 75, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    os.environ.get("AIP_STORAGE_URI"), predictor=predictor_class
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/handler.py", line 95, in __init__
INFO:google.cloud.aiplatform.docker_utils.run:    self._predictor.load(artifacts_uri)
INFO:google.cloud.aiplatform.docker_utils.run:  File "/usr/app/src_dir_handler_sdk/predictor.py", line 22, in load
INFO:google.cloud.aiplatform.docker_utils.run:    preprocessor = pickle.load(f)
INFO:google.cloud.aiplatform.docker_utils.run:ModuleNotFoundError: No module named 'preprocess'
ERROR:google.cloud.aiplatform.prediction.local_endpoint:Exception during starting serving: ('The health check never succeeded.', '', 1).
ERROR:google.cloud.aiplatform.prediction.local_endpoint:Exception during entering a context: ('The health check never succeeded.', '', 1).
---------------------------------------------------------------------------
DockerError                               Traceback (most recent call last)
/tmp/ipykernel_10717/1681702947.py in <module>
      1 with local_model.deploy_to_local_endpoint(
----> 2     artifact_uri=f"{USER_MODEL_ARTIFACTS}",
      3 ) as local_endpoint:
      4     predict_response = local_endpoint.predict(
      5         request_file=INPUT_FILE,

~/.local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/local_endpoint.py in __enter__(self)
    191         """Enters the runtime context related to this object."""
    192         try:
--> 193             self.serve()
    194         except Exception as exception:
    195             _logger.error(f"Exception during entering a context: {exception}.")

~/.local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/local_endpoint.py in serve(self)
    274             self.container_is_running = True
    275             # Waits until the model server starts.
--> 276             self._wait_until_health_check_succeeds()
    277         except Exception as exception:
    278             _logger.error(f"Exception during starting serving: {exception}.")

~/.local/lib/python3.7/site-packages/google/cloud/aiplatform/prediction/local_endpoint.py in _wait_until_health_check_succeeds(self)
    339                 message="Health check never succeeds, all container logs:",
    340             )
--> 341             raise DockerError("The health check never succeeded.", "", 1)
    342 
    343     def _stop_container_if_exists(self):

DockerError: ('The health check never succeeded.', '', 1)
```

## Steps to Reproduce the Problem

Follow [SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb)

## Specifications

- Version: google-cloud-aiplatform                 1.15.1
- Platform: google-cloud-aiplatform                 1.15.1

## Moreover there is a bug in the notebook
`LocalModel.create_cpr_model` need to be updated as `LocalModel.build_cpr_model`

@abcdefgs0324 Thank you in advance.

**Comment by abcdefgs0324** [comment]
Hi, thanks for the feedback. We are in the middle of the notebook updates.

**Comment by andrewferlitsch** [comment]
Chun-Hsiang Wang, 1 min
Hi Andrew, do you mind closing this issue since it has been fixed https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/740?
